/* Explee clone — built-in prospect database.
 * Stands in for Explee's private 75M-company / 536M-profile index.
 * Swap this array for a real API response and the rest of the app works unchanged.
 */
window.EXPLEE_DB = (function () {
  const industries = {
    fintech: "Fintech",
    saas: "SaaS",
    ecommerce: "E-commerce",
    health: "HealthTech",
    ai: "AI / ML",
    marketing: "Marketing",
    edtech: "EdTech",
    logistics: "Logistics",
    cyber: "Cybersecurity",
    green: "CleanTech",
  };

  // helper to build a company quickly
  let idc = 0;
  const C = (o) => ({
    id: "co_" + (++idc),
    ...o,
    domain: o.domain,
    website: "https://" + o.domain,
  });

  const companies = [
    C({ name: "NimbusPay", domain: "nimbuspay.io", industry: "Fintech", sub: "Payments infrastructure",
      country: "United Kingdom", city: "London", size: 24, revenue: "$3M–$5M", founded: 2021,
      tags: ["payments", "api", "b2b", "cards", "fintech"],
      desc: "Embedded payments API that lets startups issue cards and move money in minutes.",
      contacts: [
        { name: "Priya Shah", title: "CEO & Co-founder", seniority: "C-Suite", email: "priya@nimbuspay.io", verified: true, linkedin: "in/priyashah" },
        { name: "Tom Errington", title: "Head of Growth", seniority: "Head", email: "tom@nimbuspay.io", verified: true, linkedin: "in/tomerrington" },
      ] }),
    C({ name: "Ledgerly", domain: "ledgerly.co", industry: "Fintech", sub: "Accounting automation",
      country: "United Kingdom", city: "Manchester", size: 18, revenue: "$1M–$3M", founded: 2022,
      tags: ["accounting", "automation", "fintech", "smb", "api"],
      desc: "AI bookkeeping that reconciles invoices and files taxes for small businesses.",
      contacts: [
        { name: "Sarah Nolan", title: "Founder", seniority: "C-Suite", email: "sarah@ledgerly.co", verified: true, linkedin: "in/sarahnolan" },
      ] }),
    C({ name: "Vaultline", domain: "vaultline.eu", industry: "Fintech", sub: "Treasury management",
      country: "Germany", city: "Berlin", size: 42, revenue: "$5M–$10M", founded: 2020,
      tags: ["treasury", "banking", "fintech", "b2b", "cash"],
      desc: "Cash-flow and treasury platform for scaling European companies.",
      contacts: [
        { name: "Lena Vogt", title: "CFO", seniority: "C-Suite", email: "lena.vogt@vaultline.eu", verified: true, linkedin: "in/lenavogt" },
        { name: "Marco Bauer", title: "VP Sales", seniority: "VP", email: "marco@vaultline.eu", verified: false, linkedin: "in/marcobauer" },
      ] }),
    C({ name: "PennyRoot", domain: "pennyroot.com", industry: "Fintech", sub: "Consumer lending",
      country: "United States", city: "Austin", size: 67, revenue: "$10M–$25M", founded: 2019,
      tags: ["lending", "credit", "fintech", "consumer", "ml"],
      desc: "Fair-credit lending marketplace powered by alternative-data underwriting.",
      contacts: [
        { name: "Devon Price", title: "Chief Executive Officer", seniority: "C-Suite", email: "devon@pennyroot.com", verified: true, linkedin: "in/devonprice" },
      ] }),
    C({ name: "Cloudscribe", domain: "cloudscribe.io", industry: "SaaS", sub: "Developer tools",
      country: "United States", city: "San Francisco", size: 55, revenue: "$5M–$10M", founded: 2020,
      tags: ["devtools", "saas", "api", "docs", "developers"],
      desc: "Auto-generated, always-up-to-date API documentation for engineering teams.",
      contacts: [
        { name: "Maya Chen", title: "Co-founder & CTO", seniority: "C-Suite", email: "maya@cloudscribe.io", verified: true, linkedin: "in/mayachen" },
        { name: "Raj Patel", title: "Director of Marketing", seniority: "Director", email: "raj@cloudscribe.io", verified: true, linkedin: "in/rajpatel" },
      ] }),
    C({ name: "Taskloop", domain: "taskloop.app", industry: "SaaS", sub: "Project management",
      country: "Canada", city: "Toronto", size: 31, revenue: "$3M–$5M", founded: 2021,
      tags: ["productivity", "saas", "project", "teams", "b2b"],
      desc: "Lightweight project management that turns meeting notes into tracked tasks.",
      contacts: [
        { name: "Aisha Rahman", title: "CEO", seniority: "C-Suite", email: "aisha@taskloop.app", verified: true, linkedin: "in/aisharahman" },
      ] }),
    C({ name: "Formcastle", domain: "formcastle.com", industry: "SaaS", sub: "No-code forms",
      country: "United States", city: "Denver", size: 12, revenue: "$1M–$3M", founded: 2022,
      tags: ["nocode", "forms", "saas", "smb", "automation"],
      desc: "Drag-and-drop forms and workflows for teams that can't code.",
      contacts: [
        { name: "Grace Miller", title: "Founder & CEO", seniority: "C-Suite", email: "grace@formcastle.com", verified: true, linkedin: "in/gracemiller" },
      ] }),
    C({ name: "Shipfox", domain: "shipfox.io", industry: "Logistics", sub: "Last-mile delivery",
      country: "United States", city: "Chicago", size: 140, revenue: "$25M–$50M", founded: 2017,
      tags: ["logistics", "delivery", "supply-chain", "b2b", "ops"],
      desc: "Routing and tracking platform for regional last-mile delivery fleets.",
      contacts: [
        { name: "Carlos Mendes", title: "VP of Operations", seniority: "VP", email: "carlos@shipfox.io", verified: true, linkedin: "in/carlosmendes" },
        { name: "Emily Ford", title: "Head of Partnerships", seniority: "Head", email: "emily@shipfox.io", verified: true, linkedin: "in/emilyford" },
      ] }),
    C({ name: "Cratewise", domain: "cratewise.com", industry: "Logistics", sub: "Warehouse software",
      country: "Netherlands", city: "Rotterdam", size: 76, revenue: "$10M–$25M", founded: 2018,
      tags: ["warehouse", "logistics", "inventory", "b2b", "saas"],
      desc: "Warehouse management system for mid-market fulfillment operators.",
      contacts: [
        { name: "Jeroen Visser", title: "Chief Operating Officer", seniority: "C-Suite", email: "jeroen@cratewise.com", verified: true, linkedin: "in/jeroenvisser" },
      ] }),
    C({ name: "MediMind", domain: "medimind.health", industry: "HealthTech", sub: "Clinical AI",
      country: "United States", city: "Boston", size: 88, revenue: "$10M–$25M", founded: 2019,
      tags: ["health", "ai", "clinical", "b2b", "ml"],
      desc: "Ambient AI scribe that drafts clinical notes from patient visits.",
      contacts: [
        { name: "Dr. Nina Okafor", title: "Chief Medical Officer", seniority: "C-Suite", email: "nina@medimind.health", verified: true, linkedin: "in/ninaokafor" },
        { name: "Ben Stein", title: "VP Sales", seniority: "VP", email: "ben@medimind.health", verified: true, linkedin: "in/benstein" },
      ] }),
    C({ name: "Pulsecare", domain: "pulsecare.io", industry: "HealthTech", sub: "Remote monitoring",
      country: "United Kingdom", city: "Bristol", size: 29, revenue: "$3M–$5M", founded: 2021,
      tags: ["health", "monitoring", "devices", "b2b", "iot"],
      desc: "Remote patient-monitoring platform for chronic-care clinics.",
      contacts: [
        { name: "Olivia Grant", title: "CEO", seniority: "C-Suite", email: "olivia@pulsecare.io", verified: true, linkedin: "in/oliviagrant" },
      ] }),
    C({ name: "Neurabit", domain: "neurabit.ai", industry: "AI / ML", sub: "LLM infrastructure",
      country: "United States", city: "San Francisco", size: 47, revenue: "$5M–$10M", founded: 2022,
      tags: ["ai", "llm", "infra", "developers", "ml"],
      desc: "Fine-tuning and evaluation platform for teams shipping LLM features.",
      contacts: [
        { name: "Ivan Petrov", title: "Co-founder & CEO", seniority: "C-Suite", email: "ivan@neurabit.ai", verified: true, linkedin: "in/ivanpetrov" },
        { name: "Hannah Cole", title: "Head of Growth", seniority: "Head", email: "hannah@neurabit.ai", verified: true, linkedin: "in/hannahcole" },
      ] }),
    C({ name: "Visionary Labs", domain: "visionarylabs.ai", industry: "AI / ML", sub: "Computer vision",
      country: "France", city: "Paris", size: 34, revenue: "$3M–$5M", founded: 2020,
      tags: ["ai", "vision", "manufacturing", "b2b", "ml"],
      desc: "Computer-vision quality inspection for manufacturing lines.",
      contacts: [
        { name: "Camille Laurent", title: "CTO", seniority: "C-Suite", email: "camille@visionarylabs.ai", verified: false, linkedin: "in/camillelaurent" },
      ] }),
    C({ name: "Cartwheel", domain: "cartwheel.shop", industry: "E-commerce", sub: "DTC brand tools",
      country: "United States", city: "Los Angeles", size: 61, revenue: "$10M–$25M", founded: 2018,
      tags: ["ecommerce", "dtc", "retail", "saas", "marketing"],
      desc: "Post-purchase upsell and subscription tooling for DTC brands.",
      contacts: [
        { name: "Jordan Blake", title: "CEO", seniority: "C-Suite", email: "jordan@cartwheel.shop", verified: true, linkedin: "in/jordanblake" },
        { name: "Nia Roberts", title: "Director of Growth", seniority: "Director", email: "nia@cartwheel.shop", verified: true, linkedin: "in/niaroberts" },
      ] }),
    C({ name: "Bundl", domain: "bundl.store", industry: "E-commerce", sub: "Checkout",
      country: "Canada", city: "Vancouver", size: 22, revenue: "$1M–$3M", founded: 2021,
      tags: ["ecommerce", "checkout", "payments", "dtc", "saas"],
      desc: "One-click checkout that boosts conversion for Shopify merchants.",
      contacts: [
        { name: "Liam Fraser", title: "Founder", seniority: "C-Suite", email: "liam@bundl.store", verified: true, linkedin: "in/liamfraser" },
      ] }),
    C({ name: "Growthhive", domain: "growthhive.com", industry: "Marketing", sub: "Marketing automation",
      country: "United States", city: "New York", size: 95, revenue: "$10M–$25M", founded: 2017,
      tags: ["marketing", "automation", "email", "b2b", "saas"],
      desc: "Multichannel marketing automation for mid-market B2B teams.",
      contacts: [
        { name: "Rachel Kim", title: "VP Marketing", seniority: "VP", email: "rachel@growthhive.com", verified: true, linkedin: "in/rachelkim" },
        { name: "Sam Turner", title: "Head of Demand Gen", seniority: "Head", email: "sam@growthhive.com", verified: true, linkedin: "in/samturner" },
      ] }),
    C({ name: "Clickforge", domain: "clickforge.io", industry: "Marketing", sub: "Ad optimization",
      country: "Australia", city: "Sydney", size: 27, revenue: "$3M–$5M", founded: 2021,
      tags: ["marketing", "ads", "ppc", "ai", "saas"],
      desc: "AI ad-spend optimizer for performance marketing agencies.",
      contacts: [
        { name: "Mia Nguyen", title: "CEO & Founder", seniority: "C-Suite", email: "mia@clickforge.io", verified: true, linkedin: "in/mianguyen" },
      ] }),
    C({ name: "Lernova", domain: "lernova.edu", industry: "EdTech", sub: "Corporate training",
      country: "United Kingdom", city: "Edinburgh", size: 44, revenue: "$5M–$10M", founded: 2019,
      tags: ["edtech", "training", "lms", "b2b", "saas"],
      desc: "Skills platform that maps employee learning to business outcomes.",
      contacts: [
        { name: "David Osei", title: "Chief Executive Officer", seniority: "C-Suite", email: "david@lernova.edu", verified: true, linkedin: "in/davidosei" },
      ] }),
    C({ name: "Studybyte", domain: "studybyte.app", industry: "EdTech", sub: "K-12 learning",
      country: "India", city: "Bengaluru", size: 120, revenue: "$10M–$25M", founded: 2018,
      tags: ["edtech", "k12", "mobile", "consumer", "ai"],
      desc: "Adaptive learning app for K-12 exam prep across India.",
      contacts: [
        { name: "Ananya Iyer", title: "Co-founder", seniority: "C-Suite", email: "ananya@studybyte.app", verified: false, linkedin: "in/ananyaiyer" },
      ] }),
    C({ name: "Sentrix", domain: "sentrix.security", industry: "Cybersecurity", sub: "Cloud security",
      country: "United States", city: "Seattle", size: 73, revenue: "$10M–$25M", founded: 2019,
      tags: ["cyber", "cloud", "security", "b2b", "saas"],
      desc: "Cloud-native security posture management for engineering teams.",
      contacts: [
        { name: "Kevin Zhao", title: "CISO", seniority: "C-Suite", email: "kevin@sentrix.security", verified: true, linkedin: "in/kevinzhao" },
        { name: "Laura Diaz", title: "VP Sales", seniority: "VP", email: "laura@sentrix.security", verified: true, linkedin: "in/lauradiaz" },
      ] }),
    C({ name: "Phishwall", domain: "phishwall.io", industry: "Cybersecurity", sub: "Email security",
      country: "Ireland", city: "Dublin", size: 19, revenue: "$1M–$3M", founded: 2022,
      tags: ["cyber", "email", "security", "smb", "ai"],
      desc: "AI email-threat detection for small and mid-sized businesses.",
      contacts: [
        { name: "Sean Murphy", title: "Founder & CEO", seniority: "C-Suite", email: "sean@phishwall.io", verified: true, linkedin: "in/seanmurphy" },
      ] }),
    C({ name: "Voltaic", domain: "voltaic.energy", industry: "CleanTech", sub: "Solar software",
      country: "United States", city: "Phoenix", size: 58, revenue: "$5M–$10M", founded: 2018,
      tags: ["green", "solar", "energy", "b2b", "saas"],
      desc: "Design and quoting software for residential solar installers.",
      contacts: [
        { name: "Alex Rivera", title: "CEO", seniority: "C-Suite", email: "alex@voltaic.energy", verified: true, linkedin: "in/alexrivera" },
      ] }),
    C({ name: "Terrametric", domain: "terrametric.eco", industry: "CleanTech", sub: "Carbon accounting",
      country: "Sweden", city: "Stockholm", size: 36, revenue: "$3M–$5M", founded: 2020,
      tags: ["green", "carbon", "esg", "b2b", "saas"],
      desc: "Carbon-accounting platform that automates supply-chain emissions reporting.",
      contacts: [
        { name: "Freja Lindqvist", title: "Co-founder & CEO", seniority: "C-Suite", email: "freja@terrametric.eco", verified: true, linkedin: "in/frejalindqvist" },
        { name: "Erik Holm", title: "Head of Sales", seniority: "Head", email: "erik@terrametric.eco", verified: false, linkedin: "in/erikholm" },
      ] }),
    C({ name: "Quantifi", domain: "quantifi.io", industry: "SaaS", sub: "Analytics",
      country: "United Kingdom", city: "London", size: 15, revenue: "$1M–$3M", founded: 2022,
      tags: ["analytics", "saas", "data", "b2b", "api"],
      desc: "Product analytics for early-stage teams who hate configuring dashboards.",
      contacts: [
        { name: "Yusuf Ali", title: "Founder", seniority: "C-Suite", email: "yusuf@quantifi.io", verified: true, linkedin: "in/yusufali" },
      ] }),
    C({ name: "Hireflow", domain: "hireflow.work", industry: "SaaS", sub: "HR tech",
      country: "United States", city: "Atlanta", size: 40, revenue: "$5M–$10M", founded: 2020,
      tags: ["hr", "recruiting", "saas", "b2b", "ai"],
      desc: "AI applicant screening and scheduling for high-volume recruiters.",
      contacts: [
        { name: "Tanya Brooks", title: "CEO", seniority: "C-Suite", email: "tanya@hireflow.work", verified: true, linkedin: "in/tanyabrooks" },
      ] }),
    C({ name: "Payglide", domain: "payglide.co", industry: "Fintech", sub: "Payroll",
      country: "United States", city: "Miami", size: 52, revenue: "$5M–$10M", founded: 2019,
      tags: ["payroll", "fintech", "hr", "b2b", "api"],
      desc: "Global contractor payroll and compliance in 90+ countries.",
      contacts: [
        { name: "Sofia Moreno", title: "COO", seniority: "C-Suite", email: "sofia@payglide.co", verified: true, linkedin: "in/sofiamoreno" },
      ] }),
    C({ name: "Datawharf", domain: "datawharf.io", industry: "AI / ML", sub: "Data pipelines",
      country: "Germany", city: "Munich", size: 63, revenue: "$10M–$25M", founded: 2018,
      tags: ["ai", "data", "pipelines", "b2b", "infra"],
      desc: "Managed data pipelines that feed analytics and ML workloads.",
      contacts: [
        { name: "Klaus Berger", title: "CTO", seniority: "C-Suite", email: "klaus@datawharf.io", verified: true, linkedin: "in/klausberger" },
        { name: "Petra Wolf", title: "VP Marketing", seniority: "VP", email: "petra@datawharf.io", verified: true, linkedin: "in/petrawolf" },
      ] }),
    C({ name: "Foldr", domain: "foldr.app", industry: "SaaS", sub: "Document AI",
      country: "Canada", city: "Montreal", size: 26, revenue: "$3M–$5M", founded: 2021,
      tags: ["saas", "documents", "ai", "b2b", "automation"],
      desc: "Extracts structured data from contracts and invoices automatically.",
      contacts: [
        { name: "Marc Tremblay", title: "Founder & CEO", seniority: "C-Suite", email: "marc@foldr.app", verified: true, linkedin: "in/marctremblay" },
      ] }),
    C({ name: "Roамio", domain: "roamio.travel", industry: "E-commerce", sub: "Travel tech",
      country: "Spain", city: "Barcelona", size: 48, revenue: "$5M–$10M", founded: 2019,
      tags: ["travel", "ecommerce", "consumer", "marketplace", "mobile"],
      desc: "Curated boutique-hotel marketplace for independent travelers.",
      contacts: [
        { name: "Lucia Fernandez", title: "CEO", seniority: "C-Suite", email: "lucia@roamio.travel", verified: true, linkedin: "in/luciafernandez" },
      ] }),
    C({ name: "Meshify", domain: "meshify.io", industry: "AI / ML", sub: "IoT analytics",
      country: "United States", city: "Portland", size: 39, revenue: "$3M–$5M", founded: 2020,
      tags: ["iot", "ai", "sensors", "b2b", "data"],
      desc: "Predictive maintenance analytics for industrial IoT sensors.",
      contacts: [
        { name: "Chris Walker", title: "Co-founder", seniority: "C-Suite", email: "chris@meshify.io", verified: false, linkedin: "in/chriswalker" },
      ] }),
    C({ name: "Brightbill", domain: "brightbill.com", industry: "Fintech", sub: "Billing",
      country: "United Kingdom", city: "Leeds", size: 21, revenue: "$1M–$3M", founded: 2022,
      tags: ["billing", "fintech", "subscriptions", "saas", "api"],
      desc: "Usage-based billing engine for subscription and API businesses.",
      contacts: [
        { name: "Hollie Ward", title: "Founder & CEO", seniority: "C-Suite", email: "hollie@brightbill.com", verified: true, linkedin: "in/hollieward" },
      ] }),
    C({ name: "Sproutly", domain: "sproutly.io", industry: "Marketing", sub: "Social media",
      country: "United States", city: "Nashville", size: 33, revenue: "$3M–$5M", founded: 2020,
      tags: ["marketing", "social", "content", "smb", "saas"],
      desc: "AI social scheduler and content generator for small teams.",
      contacts: [
        { name: "Bianca Reyes", title: "CEO", seniority: "C-Suite", email: "bianca@sproutly.io", verified: true, linkedin: "in/biancareyes" },
      ] }),
    C({ name: "Kingfisher Health", domain: "kingfisher.health", industry: "HealthTech", sub: "Telehealth",
      country: "Australia", city: "Melbourne", size: 82, revenue: "$10M–$25M", founded: 2018,
      tags: ["health", "telehealth", "consumer", "b2b", "mobile"],
      desc: "Telehealth platform connecting rural patients with specialists.",
      contacts: [
        { name: "Noah Wilson", title: "CEO", seniority: "C-Suite", email: "noah@kingfisher.health", verified: true, linkedin: "in/noahwilson" },
        { name: "Ella Brown", title: "Head of Partnerships", seniority: "Head", email: "ella@kingfisher.health", verified: true, linkedin: "in/ellabrown" },
      ] }),
    C({ name: "Forgeworks", domain: "forgeworks.dev", industry: "SaaS", sub: "CI/CD",
      country: "United States", city: "San Francisco", size: 29, revenue: "$3M–$5M", founded: 2021,
      tags: ["devtools", "cicd", "saas", "developers", "infra"],
      desc: "Faster, cheaper CI pipelines for fast-moving engineering teams.",
      contacts: [
        { name: "Omar Haddad", title: "Co-founder & CEO", seniority: "C-Suite", email: "omar@forgeworks.dev", verified: true, linkedin: "in/omarhaddad" },
      ] }),
    C({ name: "Trustpath", domain: "trustpath.io", industry: "Cybersecurity", sub: "Identity",
      country: "Singapore", city: "Singapore", size: 45, revenue: "$5M–$10M", founded: 2020,
      tags: ["cyber", "identity", "fraud", "b2b", "api"],
      desc: "Identity verification and fraud prevention API for fintechs.",
      contacts: [
        { name: "Wei Lim", title: "CEO", seniority: "C-Suite", email: "wei@trustpath.io", verified: true, linkedin: "in/weilim" },
      ] }),
    C({ name: "Harvestly", domain: "harvestly.farm", industry: "CleanTech", sub: "AgTech",
      country: "United States", city: "Sacramento", size: 54, revenue: "$5M–$10M", founded: 2019,
      tags: ["green", "agtech", "iot", "b2b", "data"],
      desc: "Precision-agriculture software that cuts water and fertilizer waste.",
      contacts: [
        { name: "Gabriel Santos", title: "CEO & Founder", seniority: "C-Suite", email: "gabriel@harvestly.farm", verified: true, linkedin: "in/gabrielsantos" },
      ] }),
    C({ name: "Slatepay", domain: "slatepay.africa", industry: "Fintech", sub: "Mobile money",
      country: "Nigeria", city: "Lagos", size: 110, revenue: "$10M–$25M", founded: 2018,
      tags: ["fintech", "payments", "mobile", "consumer", "africa"],
      desc: "Mobile-money wallet and merchant payments across West Africa.",
      contacts: [
        { name: "Chinwe Obi", title: "CEO", seniority: "C-Suite", email: "chinwe@slatepay.africa", verified: true, linkedin: "in/chinweobi" },
        { name: "Tunde Bello", title: "VP Growth", seniority: "VP", email: "tunde@slatepay.africa", verified: false, linkedin: "in/tundebello" },
      ] }),
    C({ name: "Pixelmint", domain: "pixelmint.design", industry: "Marketing", sub: "Creative tools",
      country: "United Kingdom", city: "London", size: 17, revenue: "$1M–$3M", founded: 2022,
      tags: ["marketing", "design", "creative", "smb", "ai"],
      desc: "AI brand-asset generator for agencies and in-house creative teams.",
      contacts: [
        { name: "Ruby Hall", title: "Founder", seniority: "C-Suite", email: "ruby@pixelmint.design", verified: true, linkedin: "in/rubyhall" },
      ] }),
  ];

  // Fix a stray non-ascii name introduced above
  companies.forEach((c) => { if (c.name === "Roамio") c.name = "Roamio"; });

  return { companies, industries };
})();
